name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm config set legacy-peer-deps true
        npm install
        npm run-script build
      env:
        REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
        BRANCH: gh-pages
        FOLDER: dist
        publish_dir: ../build
